//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///echo --------------------------------------------------------------------------------
        ///echo Clean Memory
        ///echo --------------------------------------------------------------------------------
        ///echo.
        ///echo Cleaning Memory from unwanted stuffs...
        ///ping localhost -n 3 &gt;nul
        ///del /s /f /q c:\windows\temp\*.*
        ///rd /s /q c:\windows\temp
        ///md c:\windows\temp
        ///del /s /f /q C:\WINDOWS\Prefetch
        ///del /s /f /q %temp%\*.*
        ///rd /s /q %temp%
        ///md %temp%
        ///cls
        ///cls
        ///echo ----------------------------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string clean {
            get {
                return ResourceManager.GetString("clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close1 {
            get {
                object obj = ResourceManager.GetObject("close1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closedown {
            get {
                object obj = ResourceManager.GetObject("closedown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeover {
            get {
                object obj = ResourceManager.GetObject("closeover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///echo --------------------------------------------------------------------------------
        ///echo Delete Internet Cookies
        ///echo --------------------------------------------------------------------------------
        ///echo.
        ///echo Deleting Cookies...
        ///ping localhost -n 3 &gt;nul
        ///del /f /q &quot;%userprofile%\Cookies\*.*&quot;
        ///cls
        ///echo --------------------------------------------------------------------------------
        ///echo Delete Internet Cookies
        ///echo ------------------------------------------------------------------------ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cookies {
            get {
                return ResourceManager.GetString("cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///echo --------------------------------------------------------------------------------
        ///echo Disk Defragment
        ///echo --------------------------------------------------------------------------------
        ///echo.
        ///echo Defragmenting hard disks...
        ///ping localhost -n 3 &gt;nul
        ///defrag -c -v
        ///cls
        ///echo --------------------------------------------------------------------------------
        ///echo Disk Defragment
        ///echo --------------------------------------------------------------------------------
        ///echo.
        ///echo Disk Defrag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string def {
            get {
                return ResourceManager.GetString("def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///echo --------------------------------------------------------------------------------
        ///echo Disk Cleanup
        ///echo --------------------------------------------------------------------------------
        ///echo.
        ///echo Running Disk Cleanup...
        ///ping localhost -n 3 &gt;nul
        ///if exist &quot;C:\WINDOWS\temp&quot;del /f /q &quot;C:WINDOWS\temp\*.*&quot;
        ///if exist &quot;C:\WINDOWS\tmp&quot; del /f /q &quot;C:\WINDOWS\tmp\*.*&quot;
        ///if exist &quot;C:\tmp&quot; del /f /q &quot;C:\tmp\*.*&quot;
        ///if exist &quot;C:\temp&quot; del /f /q &quot;C:\temp\*.*&quot;
        ///if exist &quot;%temp%&quot; del /f /q &quot;%temp%\*.*&quot;
        ///i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string diskclean {
            get {
                return ResourceManager.GetString("diskclean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image1 {
            get {
                object obj = ResourceManager.GetObject("Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///echo --------------------------------------------------------------------------------
        ///echo Delete Temporary Internet Files
        ///echo --------------------------------------------------------------------------------
        ///echo.
        ///echo Deleting Temporary Files...
        ///ping localhost -n 3 &gt;nul
        ///del /f /q &quot;%userprofile%\AppData\Local\Microsoft\Windows\Temporary Internet Files\*.*&quot;
        ///cls
        ///echo --------------------------------------------------------------------------------
        ///echo Delete Temporary Internet Files
        ///echo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string internet {
            get {
                return ResourceManager.GetString("internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize {
            get {
                object obj = ResourceManager.GetObject("minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimizedown {
            get {
                object obj = ResourceManager.GetObject("minimizedown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimizeover {
            get {
                object obj = ResourceManager.GetObject("minimizeover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Movie2 {
            get {
                object obj = ResourceManager.GetObject("Movie2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oneclick {
            get {
                object obj = ResourceManager.GetObject("oneclick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oneclickdown {
            get {
                object obj = ResourceManager.GetObject("oneclickdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oneclickover {
            get {
                object obj = ResourceManager.GetObject("oneclickover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
